language:
- objective-c
- c++

compiler:
- clang

sudo: false
os: osx
osx_image: xcode7.3

script:
- mkdir build
- cd build
- cmake -G Xcode ..
- cmake --build . --config Release
#- cmake --test
- cd ..
- PACKAGE_NAME=`echo $TRAVIS_REPO_SLUG | sed 's/.*\///g'`
- PACKAGE_REV=`echo $TRAVIS_COMMIT | sed -e 's/^[[:alnum:]]\{6\}/&-/g' | sed 's/-.*//'`
- mkdir $PACKAGE_NAME
- if [ -e *.json ]; then cp *.json $PACKAGE_NAME; fi
- if [ -e *.md ]; then cp *.json $PACKAGE_NAME; fi
- if [ -e *.png ]; then cp *.json $PACKAGE_NAME; fi
- if [ -d docs ]; then cp -r docs $PACKAGE_NAME; fi
- if [ -d externals ]; then cp -r externals $PACKAGE_NAME; fi
- if [ -d extras ]; then cp -r extras $PACKAGE_NAME; fi
- if [ -d help ]; then cp -r help $PACKAGE_NAME; fi
- if [ -d init ]; then cp -r init $PACKAGE_NAME; fi
- if [ -d javascript ]; then cp -r javascript $PACKAGE_NAME; fi
- if [ -d media ]; then cp -r media $PACKAGE_NAME; fi
- if [ -d misc ]; then cp -r misc $PACKAGE_NAME; fi
- if [ -d patchers ]; then cp -r help $PACKAGE_NAME; fi
- zip -r $PACKAGE_NAME-$PACKAGE_REV.zip $PACKAGE_NAME

addons:
  artifacts:
    s3_region: us-west-2
    paths:
    - "$PACKAGE_NAME-$PACKAGE_REV.zip"

deploy:
  provider: s3
  access_key_id: AKIAIWE3SI2TMXC5AJBA
  secret_access_key:
    secure: QiUFfQycQ0n1275OhGMb50+LLC/4LK2VIkQWiveAlMCtyrd1lkZ4M/AlQNYfkAsvtatF7r2rvvXwXio1Uovdl8ms7hhMQ2gLryWSfsZ5zv2g2OToR9PXAivf7ujYtKrByldaHmtIP90HYPeH1K+mt2siO9WhkzAtjOBaanlx4dadF+qCH8LZacghzFrGOOS+0d01poZrNxsI89tKdy0k23hun5qUCY+DnDHVngfK4m6HPucsKRztvVoULspSP/kYx4ui0CKuJR17IxtqHkeMxmM6iFKzOEUPPg0j4jcWNBPtIuTULOleO0V/tOEDSsqKOwd94VsmOU4mSIO72d47Lso3AOrdHZFoMDUQcL/QWKZZu6O7M0eOLGZC1nZZ/PDUXkb+F8/9vEnHiQzW7dsRQebDcMdEbSr8+cEKxPThg7BuCcY7UHEAhDpGtjkcraJkcJ3hkGfJzY5iO0xSdk7Th5ObTlxrP+mTAFI/zgKS1mZI2LutYoI6mJv44A1TAHxO8zWVAHeCRKqU6mAK7L01cqPjJw/vG8kkIwdO0hilT+XrD4Mmp9CR1hfYxaV/U74l3m/gOPvlApE1cDKOeiHnftV7e0eHysagPUm75NV7zECCIBPidDAZtUbE+zCUJcOp8hOHQ6VGzMlkDjtQQYow0hmuoXRscl2iRR30ad/yup0=
  bucket: cycling74-ci
  on:
    repo: Cycling74/max-devkit
